### ISSUE TITLE
Can not remove Category Product

### ISSUE THREAD

**Issue by andi69** [sashas777/magento-1.6.1.x-1.6.2.x-patch-1533-5344#1]
Can not remove Category Product on each category by uncheck products and save category.

POST http://www.myexampleshop.com/index.php/admin/catalog_category/save/key/32af17a97fd37ed5cbb884481e20296c/id/138/?isAjax=true 
Status Code 500

**Comment by sashas777** [comment]
I don't think its related to the patch.

**Comment by andi69** [comment]
Yes, you are right. It came from another extension, Sorry
